const data = [
    {
        icon: "/youtube.svg", 
        title: "Youtube",
        opacity: "1",
        content: "Content Youtube",
        img: "",
        is: "youtube",
    },
    {
        icon: "/microphone.svg",
        title: "Spoiler Tracks",
        opacity: "0.95",
        content: "https://open.spotify.com/embed/show/1JXzyDG4PdoECSCvvJlpxL?utm_source: generator",
        img: "",
        is: "iframe",
    },
    {
        icon: "/microphone.svg",
        title: "Charlas Picantes Sobre Red Hot Chili Peppers",
        opacity: "0.85",
        content: "https://open.spotify.com/embed/show/1NGXwtsJRrUcU3qn4g925J?utm_source: generator",
        img: "",
        is: "iframe",
    },
    {
        icon: "/link.svg",
        title: "Spoiler Time",
        opacity: "0.75",
        content: "https://spoilertime.com/",
        img: "/spoilertime.jpeg",
        is: "url",
    },
    {
        icon: "/microphone.svg",
        title: "Nada que ver - Podcast Netflix",
        opacity: "0.65",
        content: "https://open.spotify.com/embed/show/42EFFA8sB8UiPFnunloX0Z?utm_source: generator",
        img: "",
        is: "iframe",
    },
    {
        icon: "/microphone.svg",
        title: "Un mensaje de audio que podría ser un podcast",
        opacity: "0.55",
        content: "https://open.spotify.com/embed/show/5V0L33VPtBCnBicX7ELFOA?utm_source: generator",
        img: "",
        is: "iframe",
    },
    {
        icon: "/microphone.svg",
        title: "Perdimos el Guion",
        opacity: "0.45",
        content: "https://open.spotify.com/embed/show/1Mwb0V9L0gWowx5OYfpY0Q?utm_source: generator",
        img: "",
        is: "iframe",
    },
    {
        icon: "/film.svg",
        title: "A Fanatic By Choice. Documental RHCP fans",
        opacity: "0.35",
        content: "http://afanaticbychoice.com/",
        img: "",
        is: "iframe",
    },
    {
        icon: "/headphones.svg",
        title: "Ajiputaparió: Tributo a Red Hot Chili Peppers",
        opacity: "0.25",
        content: "https://open.spotify.com/embed/artist/6a2ADnXdGhg8YHl9iQjLF5",
        img: "",
        is: "iframe",
    },
    {
        icon: "/headphones.svg",
        title: "Música: Timmy O'Tool",
        opacity: "0.15",
        content: "https://open.spotify.com/embed/artist/0qy2K3V7CfqRSRCWabyQ7H",
        img: "",
        is: "iframe",
    },
    {
        icon: "/headphones.svg",
        title: "Música: Americana Soundsystem",
        opacity: "0.10",
        content: "https://open.spotify.com/embed/artist/2pOG9zrfYoMBeANa4jKigV",
        img: "",
        is: "iframe",
    }
]

module.exports = { 
    data,
}

